[package]
name = "sudoku"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ratatui = '0.29.0'
sorted-vec = '0.8.5'

[dev-dependencies]
insta = "1.34.0"

[lints.rust]
warnings = 'deny'
